# Generated by Django 5.0.6 on 2026-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('brand_story', 'Brand story'), ('category', 'Category'), ('promo', 'Promo')], default='promo', max_length=20)),
                ('headline', models.CharField(max_length=200)),
                ('subheadline', models.CharField(blank=True, max_length=300)),
                ('eyebrow', models.CharField(blank=True, help_text="Small label above the headline (e.g. 'Spring/Summer Edit').", max_length=80)),
                ('image', models.ImageField(blank=True, help_text='Desktop image. Recommended 1920×900.', null=True, upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional separate mobile crop.', null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback URL if no file uploaded.')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=80)),
                ('cta_secondary_url', models.CharField(blank=True, max_length=255)),
                ('overlay_opacity', models.PositiveSmallIntegerField(default=30, help_text='0–80. Darkens the image for text legibility.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PopupReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='popup-reviews/')),
                ('photo_url', models.URLField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1–5')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('product_name', models.CharField(blank=True, help_text='Optional — what they bought.', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('embed_url', models.URLField(help_text='Instagram Reel URL (https://www.instagram.com/reel/...) or YouTube Shorts URL (https://youtube.com/shorts/...). Paste the public share URL — the storefront converts it to embeds.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reels/')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('creator_handle', models.CharField(blank=True, help_text='e.g. @priya.styles', max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
