# Generated by Django 5.0.6 on 2026-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_newslettersubscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="kind",
            field=models.CharField(
                choices=[
                    ("brand_story", "Brand story"),
                    ("category", "Category"),
                    ("promo", "Promo"),
                    ("split", "Split Promo (Middle)"),
                ],
                default="promo",
                max_length=20,
            ),
        ),
    ]
