# Generated by Django 5.0.6 on 2026-06-07 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_review_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Color variation image.",
                null=True,
                upload_to="variants/",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "Fabric", "Neckline"', max_length=100
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text='e.g. "100% Pure Cotton", "V Neck"', max_length=255
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
