# Generated by Django 5.0.6 on 2026-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_productvariant_image_productvariant_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="helpful_votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="not_helpful_votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile photo of the reviewer.",
                null=True,
                upload_to="reviewers/",
            ),
        ),
    ]
