# Generated by Django 5.0.6 on 2026-05-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('method', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('estimated_days_min', models.PositiveIntegerField(default=4)),
                ('estimated_days_max', models.PositiveIntegerField(default=10)),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, help_text='Free shipping when order subtotal exceeds this value (same currency).', max_digits=10, null=True)),
            ],
            options={
                'ordering': ['country', 'method'],
                'unique_together': {('country', 'method')},
            },
        ),
    ]
