# Generated by Django 5.0.6 on 2026-05-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=64)),
                ("razorpay_order_id", models.CharField(blank=True, max_length=64)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["razorpay_order_id"],
                        name="payments_pa_razorpa_aa7f87_idx",
                    ),
                    models.Index(
                        fields=["razorpay_payment_id"],
                        name="payments_pa_razorpa_2050dd_idx",
                    ),
                ],
            },
        ),
    ]
